# 系统配置
system:
  host: "0.0.0.0"
  post: 5001
  env: debug
  # env: release

# logger 日志
logger:
  level: info
  prefix: '[go_admin_api]'
  director: logger
  show_line: true
  log_in_console: true

# mysql配置
mysql:
  host: localhost
  post: 3306
  db: test
  username: root
  password: 123456
  log_level: dev
  charset: utf8
  maxIdle: 50
  maxOpen: 150

# redis配置
redis:
  address: 127.0.0.1:6379
  db: 0

# token 配置
token:
  headers: Bearer
  expireTime: 24
  secret: gin_admin_api
  issuer: admin